version: "3.8"

services:
  backend:
    build:
      context: ./pdam-backend
    container_name: laravel-app 
    volumes:
      - ./pdam-backend:/var/www/html
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: internship_laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    command: >
      sh -c "
        php artisan migrate --force &&
        php-fpm
      "
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:80" # Akses laravel di http://localhost:9000
    volumes:
      - ./pdam-backend:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network
    
  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: internship_laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  frontend:
    build:
      context: ./pdam-frontend
    container_name: nuxt-app
    ports:
      - "3000:3000"
    volumes:
      - ./pdam-frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:9000/api
      - NUXT_PUBLIC_STORAGE=http://localhost:9000/api/storage
      - NUXT_PUBLIC_API_REGION=https://wilayah.id
  
networks: 
  app-network:
    driver: bridge

volumes:
  mysql-data: