name: Build & Push Laravel and Nuxt Docker Images

on:
  push:
    branches:
      - main  # akan jalan otomatis saat push ke branch mai

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/pdam-backend
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/pdam-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ## ================= BACKEND ==================
      - name: Build Laravel Backend Docker Image
        run: docker build -t $BACKEND_IMAGE:latest ./pdam-backend

      - name: Push Laravel Backend Docker Image
        run: docker push $BACKEND_IMAGE:latest

      ## ================= FRONTEND ==================
      - name: Build Nuxt Frontend Docker Image
        run: docker build -t $FRONTEND_IMAGE:latest ./pdam-frontend

      - name: Push Nuxt Frontend Docker Image
        run: docker push $FRONTEND_IMAGE:latest
